from utils import loading_strumok_tables
from strumok import Strumok

def simulate_attack(tables):
    print("Simulation of attack\n")
    
    # Victim
    print("Victim generates data...")
    victim = Strumok(tables)
    victim.init_512([0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88], [0,0,0,0])
    
    for _ in range(5):
        victim.get_number64()
        

    hacker_s = victim.s.copy()
    hacker_r1 = victim.r1
    hacker_r2 = victim.r2
        
    real_gamma = []
    for _ in range(3):
        real_gamma.append(victim.get_number64())
        
    print(f"Got numbers: {[hex(z) for z in real_gamma]}\n")


    # Hacker
    print("Imitation of hacker's work...")
    
    hacker = Strumok(tables)
    hacker.set_partial_state(hacker_s, hacker_r1, hacker_r2)
    
    fake_gamma = []
    for _ in range(3):
        fake_gamma.append(hacker.get_number64())
        
    print(f"Generated by hacker: {[hex(z) for z in fake_gamma]}\n")


    # Verification
    print("Results: ")
    if real_gamma == fake_gamma:
        print("Hacker's job was successfully. He can read all victim's secrets :(")
    else:
        print("Error. Hacker : Victim = 0 : 1")

if __name__ == "__main__":
    my_tables = loading_strumok_tables("strumok_tables.c")
    if my_tables:
        simulate_attack(my_tables)